# Production Docker Compose configuration for Ubuntu server
# Use: docker-compose -f docker-compose.yml -f docker-compose.production.yml up -d

services:
  api:
    container_name: LibreChat-Production
    ports:
      - "3080:3080"
    depends_on:
      - mongodb
      - rag_api
    image: ghcr.io/danny-avila/librechat:latest
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=3080
      - MONGO_URI=mongodb://mongodb:27017/LibreChat
      - MEILI_HOST=http://meilisearch:7700
      - RAG_PORT=8000
      - RAG_API_URL=http://rag_api:8000
      - DOMAIN_CLIENT=http://167.99.133.236:3080
      - DOMAIN_SERVER=http://167.99.133.236:3080
      - NO_INDEX=false
      - DEBUG_LOGGING=false
      - CONSOLE_JSON=false
    volumes:
      - type: bind
        source: ./.env
        target: /app/.env
      - ./images:/app/client/public/images
      - ./uploads:/app/uploads
      - ./logs:/app/api/logs
    networks:
      - librechat-network

  mongodb:
    container_name: chat-mongodb-production
    image: mongo:latest
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=librechat2024
    volumes:
      - ./data-node:/data/db
    command: mongod --auth
    networks:
      - librechat-network

  meilisearch:
    container_name: chat-meilisearch-production
    image: getmeili/meilisearch:v1.12.3
    restart: always
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=your_meili_master_key_here
    volumes:
      - ./meili_data_v1.12:/meili_data
    networks:
      - librechat-network

  vectordb:
    container_name: vectordb-production
    image: ankane/pgvector:latest
    environment:
      POSTGRES_DB: librechat_vectordb
      POSTGRES_USER: librechat_user
      POSTGRES_PASSWORD: librechat_password_2024
    restart: always
    volumes:
      - pgdata_production:/var/lib/postgresql/data
    networks:
      - librechat-network

  rag_api:
    container_name: rag_api-production
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    environment:
      - DB_HOST=vectordb
      - RAG_PORT=8000
    restart: always
    depends_on:
      - vectordb
    env_file:
      - .env
    networks:
      - librechat-network

  # Optional: Nginx reverse proxy for better security and SSL
  nginx:
    container_name: librechat-nginx
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - api
    restart: always
    networks:
      - librechat-network

volumes:
  pgdata_production:

networks:
  librechat-network:
    driver: bridge 